# Generated by Django 5.0.7 on 2024-07-22 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecycleBin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_object', models.JSONField(blank=True, verbose_name='Objeto Excluído')),
            ],
            options={
                'verbose_name': 'Objeto Deletado',
                'verbose_name_plural': 'Objetos Deletados',
            },
        ),
    ]
