# Generated by Django 5.0.7 on 2024-08-19 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recyclebin', '0002_recyclebin_deleted_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recyclebin',
            name='deleted_by',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Excluído por'),
        ),
    ]
