# Generated by Django 5.0.7 on 2024-07-15 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Attraction',
            new_name='ToutistSpot',
        ),
    ]
