# Generated by Django 5.0.7 on 2024-07-15 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0001_initial'),
        ('core', '0002_rename_attraction_toutistspot'),
    ]

    operations = [
        migrations.AddField(
            model_name='toutistspot',
            name='attractions',
            field=models.ManyToManyField(to='attractions.attractions'),
        ),
    ]
