# Generated by Django 5.0.7 on 2024-07-16 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0002_alter_attractions_options_attractions_created_date_and_more'),
        ('comments', '0002_alter_comment_options_comment_created_date_and_more'),
        ('core', '0003_toutistspot_attractions'),
        ('ratings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TouristSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em')),
                ('updated_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em')),
                ('name', models.CharField(max_length=150, verbose_name='Nome')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('approved', models.BooleanField(default=False, verbose_name='Está aprovado?')),
                ('attractions', models.ManyToManyField(to='attractions.attractions')),
                ('comments', models.ManyToManyField(to='comments.comment')),
                ('ratings', models.ManyToManyField(to='ratings.rating')),
            ],
            options={
                'verbose_name': 'Ponto turístico',
                'verbose_name_plural': 'Pontos turísticos',
            },
        ),
        migrations.DeleteModel(
            name='ToutistSpot',
        ),
    ]
