# Generated by Django 5.0.7 on 2024-07-16 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
        ('core', '0004_touristspot_delete_toutistspot'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristspot',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='address.address'),
        ),
    ]
