# Generated by Django 5.0.7 on 2024-07-22 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0003_rename_attractions_attraction'),
        ('comments', '0002_alter_comment_options_comment_created_date_and_more'),
        ('core', '0005_touristspot_address'),
        ('ratings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touristspot',
            name='attractions',
            field=models.ManyToManyField(blank=True, related_name='attractions', to='attractions.attraction'),
        ),
        migrations.AlterField(
            model_name='touristspot',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='comments', to='comments.comment'),
        ),
        migrations.AlterField(
            model_name='touristspot',
            name='ratings',
            field=models.ManyToManyField(blank=True, related_name='ratings', to='ratings.rating'),
        ),
    ]
