# Generated by Django 5.0.7 on 2024-08-19 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_touristspot_attractions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristspot',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='tourist_spots/'),
        ),
    ]
