# Generated by Django 5.0.7 on 2024-07-16 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em')),
                ('updated_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em')),
                ('address_street', models.CharField(max_length=150)),
                ('address_city', models.CharField(max_length=150)),
                ('address_state', models.CharField(max_length=50)),
                ('address_zip', models.CharField(max_length=50)),
                ('address_country', models.CharField(max_length=70)),
                ('latitude', models.DecimalField(decimal_places=2, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
            options={
                'verbose_name': 'Endereço',
                'verbose_name_plural': 'Endereços',
            },
        ),
    ]
