# Generated by Django 5.0.7 on 2024-07-15 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attractions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(verbose_name='Descrição')),
                ('opening_hours', models.TextField(verbose_name='Horário de Funcionamento')),
                ('minimum_age', models.IntegerField(verbose_name='Idade Minima')),
            ],
        ),
    ]
