# Generated by Django 5.0.7 on 2024-07-22 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0002_alter_attractions_options_attractions_created_date_and_more'),
        ('core', '0005_touristspot_address'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Attractions',
            new_name='Attraction',
        ),
    ]
